FROM --platform=linux/amd64 ubuntu:jammy-20260509

RUN apt-get update && \
    apt-get install -y curl build-essential gdb python3 && \
    rm -rf /var/lib/apt/lists/*

# Host ./bof.c -> Container /app/bof.c
COPY bof.c /app/bof.c
WORKDIR /app

# Settings for binary execution when running a container
RUN gcc -m64 bof.c -o bof -z execstack -fno-stack-protector

CMD ["/bin/bash"]